---
# vars/main.yml file for source_control
app_user: "www-data"
http_host: "scm.dastagg.local"
http_conf: "scm.dastagg.local.conf"
http_port: "80"
disable_default: true

# Fossil variables
fossil:
  page_title: "These are the Fossil Repositories of dastagg."
  admin: "sysop"


# Main Web Page variables
main_page:
  title: "dastagg repos"
  logo_title: "dastagg repositories"
  webpage_title: "This is the home for dastagg Git and Fossil repositories."
  username1: "dastagg"
  username2: "staggsystems"
  copyright_name: "David"

# Gitolite variables
gitolite:
    user: git
    group: git
    homedir: /home/git
    admindir: /home/git/admin
    admin: gitoliteadmin
