---
# tasks/main.yml file for source control

- include: update_cache.yml

- include: install_Applications.yml

- include: configure_Apache2.yml

- include: configure_Fossil.yml

- include: configure_Gitolite.yml

- include: configure_cGit.yml

- include: service.yml
