---
# tasks/configure_Apache2.yml

- name: Create document root directory
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Copy index page
  template:
    src: http_files/index.html.j2
    dest: "/var/www/{{ http_host }}/index.html"

- name: Copy support files
  copy:
    src: files/http_files/
    dest: "/var/www/{{ http_host }}"

- name: Set up Apache virtualhost
  template:
    src: http_files/apache2.conf.j2
    dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: Enable cgi module
  shell: /usr/sbin/a2enmod cgi
  notify: Reload Apache


# This doesn't seem to work for Apache2 on Ubuntu
# - name: Enable cgi module
#   apache2_module:
#     state: present
#     name: cgi

- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache


- name: Disable default Apache site
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: Reload Apache
