---
# tasks/install.yml

- name: Install Applications
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - apache2
    - fossil
    - git
    - gitolite3
    - cgit
    - python3-docutils
    - python3-markdown
    - python3-pygments


