# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "ctrl" do |ctrl|
    ctrl.vm.box = "debian/buster64"
    ctrl.vm.box_version = "10.0.0"
    ctrl.vm.network "private_network", ip: "192.168.61.100"
    ctrl.vm.hostname = "ctrl"
  end


  config.vm.define "web1" do |web1|
    web1.vm.box = "debian/buster64"
    web1.vm.box_version = "10.0.0"
    web1.vm.network "private_network", ip: "192.168.61.110"
    web1.vm.hostname = "web1"
  end

  config.vm.define "db1" do |db1|
    db1.vm.box = "debian/buster64"
    db1.vm.box_version = "10.0.0"
    db1.vm.network "private_network", ip: "192.168.61.120"
    db1.vm.hostname = "db1"
  end

  config.vm.define "test1" do |test1|
    test1.vm.box = "hashicorp/bionic64"
    test1.vm.box_version = "1905.1"
    test1.vm.network "private_network", ip: "192.168.61.130"
    test1.vm.hostname = "test1"
  end

  config.vm.define "kubem" do |kubem|
    kubem.vm.box = "debian/buster64"
    kubem.vm.box_version = "10.0.0"
    kubem.vm.network "private_network", ip: "192.168.61.150"
    kubem.vm.hostname = "kubem"
  end

  config.vm.define "kube2" do |kube2|
    kube2.vm.box = "debian/buster64"
    kube2.vm.box_version = "10.0.0"
    kube2.vm.network "private_network", ip: "192.168.61.152"
    kube2.vm.hostname = "kube2"
  end

  config.vm.define "kube3" do |kube3|
    kube3.vm.box = "debian/buster64"
    kube3.vm.box_version = "10.0.0"
    kube3.vm.network "private_network", ip: "192.168.61.154"
    kube3.vm.hostname = "kube3"
  end

  config.vm.define "kube4" do |kube4|
    kube4.vm.box = "debian/buster64"
    kube4.vm.box_version = "10.0.0"
    kube4.vm.network "private_network", ip: "192.168.61.156"
    kube4.vm.hostname = "kube4"
  end

  config.vm.define "scm" do |scm|
    scm.vm.box = "debian/buster64"
    scm.vm.box_version = "10.0.0"
    scm.vm.hostname = "scm"
    scm.vm.network "private_network", ip: "192.168.61.160"
  end
end
